from car_sales.model import Models
from car_makes import makes

models = {
    Models(name="DB9", make=makes.makes['aston_martin']),
    Models(name="DB6", make=makes.makes['aston_martin']),
    Models(name="A4", make=makes.makes['audi']),
    Models(name="A6", make=makes.makes['audi']),
    Models(name="Q5", make=makes.makes['audi']),
    Models(name="Q7", make=makes.makes['audi']),
    Models(name="TT", make=makes.makes['audi']),
    Models(name="A1", make=makes.makes['audi']),
    Models(name="A3", make=makes.makes['audi']),
    Models(name="320", make=makes.makes['bmw']),
    Models(name="330", make=makes.makes['bmw']),
    Models(name="4 Series", make=makes.makes['bmw']),
    Models(name="3 Series", make=makes.makes['bwm']),
    Models(name="5 Series", make=makes.makes['bmw']),
    Models(name="Civic", make=makes.makes['honda']),
    Models(name="Accord", make=makes.makes['honda']),
    Models(name="NSX", make=makes.makes['honda']),
    Models(name="Jazz", make=makes.makes['honda']),
    Models(name="CR-V", make=makes.makes['honda']),
    Models(name="HR-V", make=makes.makes['honda']),
    Models(name="Prelude", make=makes.makes['honda']),
    Models(name="IS2000", make=makes.makes['lexus']),
    Models(name="6", make=makes.makes['mazda']),
    Models(name="3", make=makes.makes['mazda']),
    Models(name="RX-7", make=makes.makes['mazda']),
    Models(name="RX-8", make=makes.makes['mazda']),
    Models(name="MX-5", make=makes.makes['mazda']),
    Models(name="CX-5", make=makes.makes['mazda']),
    Models(name="Lancer Evolution X", make=makes.makes['mitsubishi']),
    Models(name="Skyline GTR-32", make=makes.makes['nissan']),
    Models(name="GTR", make=makes.makes['nissan']),
    Models(name="Skyline GTR-34", make=makes.makes['nissan']),
    Models(name="Silvia", make=makes.makes['nissan']),
    Models(name="Stagea", make=makes.makes['nissan']),
    Models(name="350Z", make=makes.makes['nissan']),
    Models(name="Fairlady Z", make=makes.makes['nissan']),
    Models(name="30Z", make=makes.makes['nissan']),
    Models(name="Impreza", make=makes.makes['subaru']),
    Models(name="BRZ", make=makes.makes['subaru']),
    Models(name="Legacy", make=makes.makes['subaru']),
    Models(name="Supra", make=makes.makes['toyota']),
    Models(name="Aristo", make=makes.makes['toyota']),
    Models(name="Avensis", make=makes.makes['toyota']),
    Models(name="Carolla", make=makes.makes['toyota']),
    Models(name="Celica", make=makes.makes['toyota']),
    Models(name="MR 2", make=makes.makes['toyota']),
    Models(name="Passat", make=makes.makes['volkswagon']),
    Models(name="Golf", make=makes.makes['volkswagon']),
    Models(name="Scirocco", make=makes.makes['volkswagon']),
    Models(name="Amarok", make=makes.makes['volkswagon'])
}