from car_sales.model import Models
from car_makes import makes

models = {
    Models(name="DB9", make=makes[0]),
    Models(name="DB6", make=makes[0]),
    Models(name="A4", make=makes[1]),
    Models(name="A6", make=makes[1]),
    Models(name="Q5", make=makes[1]),
    Models(name="Q7", make=makes[1]),
    Models(name="TT", make=makes[1]),
    Models(name="A1", make=makes[1]),
    Models(name="A3", make=makes[1]),
    Models(name="320", make=makes[2]),
    Models(name="330", make=makes[2]),
    Models(name="4 Series", make=makes[2]),
    Models(name="3 Series", make=makes[2]),
    Models(name="5 Series", make=makes[2]),
    Models(name="Civic", make=makes[3]),
    Models(name="Accord", make=makes[3]),
    Models(name="NSX", make=makes[3]),
    Models(name="Jazz", make=makes[3]),
    Models(name="CR-V", make=makes[3]),
    Models(name="HR-V", make=makes[3]),
    Models(name="Prelude", make=makes[3]),
    Models(name="IS2000", make=makes[4]),
    Models(name="6", make=makes[5]),
    Models(name="3", make=makes[5]),
    Models(name="RX-7", make=makes[5]),
    Models(name="RX-8", make=makes[5]),
    Models(name="MX-5", make=makes[5]),
    Models(name="CX-5", make=makes[5]),
    Models(name="Lancer Evolution X", make=makes[6]),
    Models(name="Skyline GTR-32", make=makes[7]),
    Models(name="GTR", make=makes[7]),
    Models(name="Skyline GTR-34", make=makes[7]),
    Models(name="Silvia", make=makes[7]),
    Models(name="Stagea", make=makes[7]),
    Models(name="350Z", make=makes[7]),
    Models(name="Fairlady Z", make=makes[7]),
    Models(name="370Z", make=makes[7]),
    Models(name="Impreza", make=makes[8]),
    Models(name="BRZ", make=makes[8]),
    Models(name="Legacy", make=makes[8]),
    Models(name="Supra", make=makes[9]),
    Models(name="Aristo", make=makes[9]),
    Models(name="Avensis", make=makes[9]),
    Models(name="Carolla", make=makes[9]),
    Models(name="Celica", make=makes[9]),
    Models(name="MR 2", make=makes[9]),
    Models(name="Passat", make=makes[10]),
    Models(name="Golf", make=makes[10]),
    Models(name="Scirocco", make=makes[10]),
    Models(name="Amarok", make=makes[10])
}