from car_sales.model import Makes

makes = {
    Makes(name="Alfa Romeo"),
    Makes(name="Aston Martin"),
    Makes(name="Audi"),
    Makes(name="BMW"),
    Makes(name="Citroen"),
    Makes(name="Fiat"),
    Makes(name="Ford"),
    Makes(name="Honda"),
    Makes(name="Hyundai"),
    Makes(name="Jaguar"),
    Makes(name="KIA"),
    Makes(name="Land Rover"),
    Makes(name="Lexus"),
    Makes(name="Mazda"),
    Makes(name="Mercedes-Benz"),
    Makes(name="Mini"),
    Makes(name="Mitsubishi"),
    Makes(name="Nissan"),
    Makes(name="Peugeot"),
    Makes(name="Porsche"),
    Makes(name="Renault"),
    Makes(name="Saab"),
    Makes(name="Seat"),
    Makes(name="Skoda"),
    Makes(name="Subaru"),
    Makes(name="Suzuki"),
    Makes(name="Toyota"),
    Makes(name="Vauxhall"),
    Makes(name="Volkswagen"),
    Makes(name="Volvo")
}