# -*- coding: utf-8 -*-
from car_sales import create_app
from car_sales.model import db
from flask_script import Manager, prompt_bool
from flask_migrate import Migrate, MigrateCommand
from car_sales.model import CarSale, Makes, Models, UsedStock, Users

app = create_app()
db.init_app(app)

migrate = Migrate(app, db)

manager = Manager(app)
manager.add_command('db', MigrateCommand)


@manager.command
def insert_data():
    aston_martin = Makes(name="Aston Martin")
    db.session.add(aston_martin)
    audi = Makes(name="Audi")
    db.session.add(audi)
    bmw = Makes(name="BMW")
    db.session.add(bmw)
    ford = Makes(name="Ford")
    db.session.add(ford)
    honda = Makes(name="Honda")
    db.session.add(honda)
    lexus = Makes(name="Lexus")
    db.session.add(lexus)
    mazda = Makes(name="Mazda")
    db.session.add(mazda)
    mitsubishi = Makes(name="Mitsubishi")
    db.session.add(mitsubishi)
    nissan = Makes(name="Nissan")
    db.session.add(nissan)
    subaru = Makes(name="Subaru")
    db.session.add(subaru)
    suzuki = Makes(name="Suzuki")
    db.session.add(suzuki)
    toyota = Makes(name="Toyota")
    db.session.add(toyota)
    volkswagon = Makes(name="Volkswagen")
    db.session.add(volkswagon)

    db9 = Models(name="DB9", make=aston_martin)
    db.session.add(db9)
    db6 = Models(name="DB6", make=aston_martin)
    db.session.add(db6)
    a4 = Models(name="A4", make=audi)
    db.session.add(a4)
    a6 = Models(name="A6", make=audi)
    db.session.add(a6)
    q5 = Models(name="Q5", make=audi)
    db.session.add(q5)
    q7 = Models(name="Q7", make=audi)
    db.session.add(q7)
    tt = Models(name="TT", make=audi)
    db.session.add(tt)
    a3 = Models(name="A3", make=audi)
    db.session.add(a3)
    bmw_320 = Models(name="320", make=bmw)
    db.session.add(bmw_320)
    bmw_330 = Models(name="330", make=bmw)
    db.session.add(bmw_330)
    civic = Models(name="Civic", make=honda)
    db.session.add(civic)
    accord = Models(name="Accord", make=honda)
    db.session.add(accord)
    nsx = Models(name="NSX", make=honda)
    db.session.add(nsx)
    prelude = Models(name="Prelude", make=honda)
    db.session.add(prelude)
    is2000 = Models(name="IS2000", make=lexus)
    db.session.add(is2000)
    mazda_6 = Models(name="6", make=mazda)
    db.session.add(mazda_6)
    mazda_3 = Models(name="3", make=mazda)
    db.session.add(mazda_3)
    rx7 = Models(name="RX-7", make=mazda)
    db.session.add(rx7)
    rx8 = Models(name="RX-8", make=mazda)
    db.session.add(rx8)
    mx5 = Models(name="MX-5", make=mazda)
    db.session.add(mx5)
    lancer = Models(name="Lancer Evolution X", make=mitsubishi)
    db.session.add(lancer)
    r32 = Models(name="Skyline GTR-32", make=nissan)
    db.session.add(r32)
    gtr = Models(name="GTR", make=nissan)
    db.session.add(gtr)
    r34 = Models(name="Skyline GTR-34", make=nissan)
    db.session.add(r34)
    silvia = Models(name="Silvia", make=nissan)
    db.session.add(silvia)
    stagea = Models(name="Stagea", make=nissan)
    db.session.add(stagea)
    fairlady_350 = Models(name="350Z", make=nissan)
    db.session.add(fairlady_350)
    fairlady = Models(name="Fairlady Z", make=nissan)
    db.session.add(fairlady)
    fairlady_370 = Models(name="370Z", make=nissan)
    db.session.add(fairlady_370)
    impreza = Models(name="Impreza", make=subaru)
    db.session.add(impreza)
    brz = Models(name="BRZ", make=subaru)
    db.session.add(brz)
    supra = Models(name="Supra", make=toyota)
    db.session.add(supra)
    avensis = Models(name="Avensis", make=toyota)
    db.session.add(avensis)
    carolla = Models(name="Carolla", make=toyota)
    db.session.add(carolla)
    passat = Models(name="Passat", make=volkswagon)
    db.session.add(passat)
    golf = Models(name="Golf", make=volkswagon)
    db.session.add(golf)
    scirocco = Models(name="Scirocco", make=volkswagon)
    db.session.add(scirocco)


@manager.command
def dropdb():
    if prompt_bool("Are you sure you want to lose all your data"):
        db.drop_all()
        print ('Dropped the database')


if __name__ == '__main__':
    manager.run()
