"""empty message

Revision ID: 75dc5f7641de
Revises: 
Create Date: 2017-08-29 20:06:54.814000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75dc5f7641de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('used_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('fuel_type', sa.String(length=10), nullable=True),
    sa.Column('engine_size', sa.String(length=8), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=True),
    sa.Column('colour', sa.String(length=10), nullable=True),
    sa.Column('transmission', sa.String(length=12), nullable=True),
    sa.Column('image_location', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Float(precision=6, asdecimal=2), nullable=False),
    sa.Column('sold', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('used_stock_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['used_stock_id'], ['used_stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    op.drop_table('users')
    op.drop_table('used_stock')
    # ### end Alembic commands ###
