"""Add Description To UsedStock

Revision ID: bc801384938f
Revises: 75dc5f7641de
Create Date: 2017-08-29 20:20:26.109000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc801384938f'
down_revision = '75dc5f7641de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('used_stock', sa.Column('description', sa.String(length=3000), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('used_stock', 'description')
    # ### end Alembic commands ###
