"""Added Makes Table to Model

Revision ID: f2c054d04cc9
Revises: f42702ba3f18
Create Date: 2017-08-31 21:47:48.256000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f2c054d04cc9'
down_revision = 'f42702ba3f18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('makes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'used_stock', sa.Column('make_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'used_stock', 'makes', ['make_id'], ['id'])
    op.drop_column(u'used_stock', 'make')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'used_stock', sa.Column('make', mysql.VARCHAR(length=50), nullable=False))
    op.drop_constraint(None, 'used_stock', type_='foreignkey')
    op.drop_column(u'used_stock', 'make_id')
    op.drop_table('makes')
    # ### end Alembic commands ###
